FROM ubuntu:17.04
   RUN apt-get update -y
   RUN apt-get install libboost-python-dev -y
   RUN apt-get install cmake -y
   RUN apt-get install vim -y
   RUN apt-get install g++ -y
   RUN apt-get install python3.6
